### ISSUE TITLE
to strict or not strict (breaking commit)

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#12]
I pulled the latest version, but got this:

```
$ node --version
4.0.0
$ node app.js 
/mnt/data/home/sqz/projects/expressa/node_modules/promise-sequential/index.js:9
    let count = 0;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/data/home/sqz/projects/expressa/index.js:8:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

Lets try strict:

```
$ node --use-strict app.js 
/mnt/data/home/sqz/projects/expressa/node_modules/bcrypt-nodejs/bCrypt.js:519
        password = password + (minor >= 'a' ? "\000" : "");
                                                ^^

SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/mnt/data/home/sqz/projects/expressa/auth/index.js:2:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

I tried looking for a newer bcrypt, but it's already at the latest version.
I think the promise-sequential requires strict mode, but bcrypt needs to run outside strict mode.
Not sure how to solve this, but i think we should find a solution as many services still run < node v4

**Comment by thomas4019** [comment]
Thanks for the detailed explanation and sorry about the breaking change. I hadn't pushed it to my server yet (which is also running v4). 

I think let's require use-strict for these old clients. I've replaced bcrypt-nodejs with bcryptjs which seems to be a lot more popular and also strict compatible.

**Comment by coderofsalvation** [comment]
awesome thanks
